# Generated by Skyramp v1.3.18 on 2026-04-24 20:28:33.040898377 +0000 UTC m=+17.082304448
# Command: skyramp generate integration rest \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--output batch_orders_creation_integration_test.py \
# 		--output-dir /home/runner/work/ebikes-lwc/ebikes-lwc/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/ebikes-lwc/ebikes-lwc/tests/scenario_batch-orders-creation.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_playful_bear_m8hbtf_dev_ed = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "https://playful-bear-m8hbtf-dev-ed.trailblaze.my.salesforce.com")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    endpoint_1_POST_request_body = r'''[
        {
            "Account__c": "001g800000C3eLNAAZ",
            "Status__c": "Draft"
        },
        {
            "Account__c": "001g800000C3eLNAAZ",
            "Status__c": "Draft"
        }
    ]'''

    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_playful_bear_m8hbtf_dev_ed,
        path="/services/apexrest/orders/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_1_POST_response, "0.Id") is not None
    assert skyramp.get_response_value(endpoint_1_POST_response, "0.Status__c") == "Draft"
    assert skyramp.get_response_value(endpoint_1_POST_response, "0.Account__c") == "001g800000C3eLNAAZ"
    assert skyramp.get_response_value(endpoint_1_POST_response, "0.LastModifiedDate") is not None
    assert skyramp.get_response_value(endpoint_1_POST_response, "1.Id") is not None
    assert skyramp.get_response_value(endpoint_1_POST_response, "1.Status__c") == "Draft"
    assert skyramp.get_response_value(endpoint_1_POST_response, "2.Id") is None

    orders = skyramp.get_response_value(endpoint_1_POST_response, "0.Id")
    orders_1 = skyramp.get_response_value(endpoint_1_POST_response, "1.Id")

    # Execute Request
    orders_GET_response = client.send_request(
        url=URL_playful_bear_m8hbtf_dev_ed,
        path="/services/apexrest/orders/{orders}",
        method="GET",
        headers=headers,
        path_params={"orders": orders}
    )
    # Generated Assertions
    assert orders_GET_response.status_code == 200
    assert skyramp.get_response_value(orders_GET_response, "Id") == skyramp.get_response_value(endpoint_1_POST_response, "0.Id")
    assert skyramp.get_response_value(orders_GET_response, "Status__c") == "Draft"
    assert skyramp.get_response_value(orders_GET_response, "Account__c") == "001g800000C3eLNAAZ"
    assert skyramp.get_response_value(orders_GET_response, "LastModifiedDate") is not None

    # Execute Request
    orders_DELETE_response = client.send_request(
        url=URL_playful_bear_m8hbtf_dev_ed,
        path="/services/apexrest/orders/{orders}",
        method="DELETE",
        headers=headers,
        path_params={"orders": orders}
    )
    # Generated Assertions
    assert orders_DELETE_response.status_code == 204

    # Execute Request
    orders_DELETE_1_response = client.send_request(
        url=URL_playful_bear_m8hbtf_dev_ed,
        path="/services/apexrest/orders/{orders}",
        method="DELETE",
        headers=headers,
        path_params={"orders": orders_1}
    )
    # Generated Assertions
    assert orders_DELETE_1_response.status_code == 204


if __name__ == "__main__":
    test_integration()
