# Generated by Skyramp v1.3.18 on 2026-04-24 20:29:43.356787103 +0000 UTC m=+87.398193154
# Command: skyramp generate contract rest https://playful-bear-m8hbtf-dev-ed.trailblaze.my.salesforce.com/services/apexrest/orders/ \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output contract_orders_get_list.py \
# 		--output-dir /home/runner/work/ebikes-lwc/ebikes-lwc/tests \
# 		--overwrite \
# 		--provider \
# 		--response-data {"response":[{"Id":"a01FAKE000001","Name":"O-00100","Status__c":"Draft","Account__c":"001g800000C3eLNAAZ","CreatedDate":"2026-04-24T00:00:00.000Z","LastModifiedDate":"2026-04-24T00:00:00.000Z"}]} \
# 		--response-status-code 200 \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "https://playful-bear-m8hbtf-dev-ed.trailblaze.my.salesforce.com")

# contract test for /services/apexrest/orders/ GET
def test_orders_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Expected Response Body
    expected_orders_GET_response_body = r'''[
        {
            "Account__c": "001g800000C3eLNAAZ",
            "CreatedDate": "2026-04-24T00:00:00.000Z",
            "Id": "a01FAKE000001",
            "LastModifiedDate": "2026-04-24T00:00:00.000Z",
            "Name": "O-00100",
            "Status__c": "Draft"
        }
    ]'''

    # Execute Request
    orders_GET_response = client.send_request(
        url=URL,
        path="/services/apexrest/orders/",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert orders_GET_response.status_code == 200
    assert skyramp.check_schema(orders_GET_response, expected_orders_GET_response_body)
    assert skyramp.get_response_value(orders_GET_response, "0.Id") is not None
    assert skyramp.get_response_value(orders_GET_response, "0.Name") is not None
    assert skyramp.get_response_value(orders_GET_response, "0.Status__c") is not None
    assert skyramp.get_response_value(orders_GET_response, "0.Account__c") is not None
    assert skyramp.get_response_value(orders_GET_response, "0.CreatedDate") is not None
    assert skyramp.get_response_value(orders_GET_response, "0.LastModifiedDate") is not None


if __name__ == "__main__":
    test_orders_get()
