# Generated by Skyramp v1.3.19 on 2026-04-23 16:54:53.603141 -0400 EDT m=+3173.679406293
# Command: skyramp generate contract rest https://playful-bear-m8hbtf-dev-ed.trailblaze.my.salesforce.com/services/data/v65.0/sobjects/Product__c/ \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output contract_sobject_product_post.py \
# 		--output-dir /Users/koljaheck/Documents/Professional/Skyramp/ebikes-lwc/tests \
# 		--overwrite \
# 		--provider \
# 		--request-data {"Name":"SObject Contract Test Bike","MSRP__c":2499,"Category__c":"Commuter","Material__c":"Aluminum","Level__c":"Beginner"} \
# 		--response-data {"id":"a03FAKE000001","success":true,"errors":[]} \
# 		--response-status-code 201 \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "https://playful-bear-m8hbtf-dev-ed.trailblaze.my.salesforce.com")

# contract test for /services/data/v65.0/sobjects/Product__c/ POST
def test_product__c_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    Product_c_POST_request_body = r'''{
        "Category__c": "Commuter",
        "Level__c": "Beginner",
        "MSRP__c": 2499,
        "Material__c": "Aluminum",
        "Name": "SObject Contract Test Bike"
    }'''

    # Expected Response Body
    expected_Product_c_POST_response_body = r'''{
        "errors": [],
        "id": "a03FAKE000001",
        "success": true
    }'''

    # Execute Request
    Product_c_POST_response = client.send_request(
        url=URL,
        path="/services/data/v65.0/sobjects/Product__c/",
        method="POST",
        body=Product_c_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert Product_c_POST_response.status_code == 201
    assert skyramp.check_schema(Product_c_POST_response, expected_Product_c_POST_response_body)
    assert skyramp.get_response_value(Product_c_POST_response, "id") is not None
    assert skyramp.get_response_value(Product_c_POST_response, "success") == True

    # Cleanup: delete the created product
    product_id = skyramp.get_response_value(Product_c_POST_response, "id")
    client.send_request(
        url=URL,
        path=f"/services/data/v65.0/sobjects/Product__c/{product_id}",
        method="DELETE",
        headers=headers
    )


if __name__ == "__main__":
    test_product__c_post()
