# Generated by Skyramp v1.3.18 on 2026-04-24 20:29:47.578602136 +0000 UTC m=+91.620008217
# Command: skyramp generate contract rest https://playful-bear-m8hbtf-dev-ed.trailblaze.my.salesforce.com/services/apexrest/orders/ \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output contract_orders_batch_post_error.py \
# 		--output-dir /home/runner/work/ebikes-lwc/ebikes-lwc/tests \
# 		--overwrite \
# 		--provider \
# 		--request-data [{"Account__c":"INVALID_ACCOUNT_ID_000","Status__c":"Draft"}] \
# 		--response-data {"error":"DML operation failed"} \
# 		--response-status-code 400 \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "https://playful-bear-m8hbtf-dev-ed.trailblaze.my.salesforce.com")

# contract test for /services/apexrest/orders/ POST
def test_orders_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    orders_POST_request_body = r'''[
        {
            "Account__c": "INVALID_ACCOUNT_ID_000",
            "Status__c": "Draft"
        }
    ]'''

    # Expected Response Body
    expected_orders_POST_response_body = r'''{
        "error": "DML operation failed"
    }'''

    # Execute Request
    orders_POST_response = client.send_request(
        url=URL,
        path="/services/apexrest/orders/",
        method="POST",
        body=orders_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert orders_POST_response.status_code == 400
    assert skyramp.check_schema(orders_POST_response, expected_orders_POST_response_body)
    assert skyramp.get_response_value(orders_POST_response, "error") is not None


if __name__ == "__main__":
    test_orders_post()
