# Generated by Skyramp v1.3.18 on 2026-04-24 18:37:09.614148872 +0000 UTC m=+28.171921967
# Command: skyramp generate contract rest https://playful-bear-m8hbtf-dev-ed.trailblaze.my.salesforce.com/services/apexrest/orders/{order_id} \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output contract_orders_get.py \
# 		--output-dir /home/runner/work/ebikes-lwc/ebikes-lwc/tests \
# 		--overwrite \
# 		--path-params order_id=a01g800000C3eLNAAZ \
# 		--provider \
# 		--response-data {"Id":"a01g800000C3eLNAAZ","Name":"O-00001","Status__c":"Draft","Account__c":"001g800000C3eLNAAZ","CreatedDate":"2026-04-24T18:00:00.000Z","LastModifiedDate":"2026-04-24T18:00:00.000Z"} \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "https://playful-bear-m8hbtf-dev-ed.trailblaze.my.salesforce.com")

# contract test for /services/apexrest/orders/{order_id} GET
def test_orders_order_id_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    order_id = "a01g800000C3eLNAAZ"

    # Expected Response Body
    expected_orders_order_id_GET_response_body = r'''{
        "Account__c": "001g800000C3eLNAAZ",
        "CreatedDate": "2026-04-24T18:00:00.000Z",
        "Id": "a01g800000C3eLNAAZ",
        "LastModifiedDate": "2026-04-24T18:00:00.000Z",
        "Name": "O-00001",
        "Status__c": "Draft"
    }'''

    # Execute Request
    orders_order_id_GET_response = client.send_request(
        url=URL,
        path="/services/apexrest/orders/{order_id}",
        method="GET",
        headers=headers,
        path_params={"order_id": order_id}
    )

    # Generated Assertions
    assert skyramp.check_status_code(orders_order_id_GET_response, "20x")
    assert skyramp.check_schema(orders_order_id_GET_response, expected_orders_order_id_GET_response_body)
    assert skyramp.get_response_value(orders_order_id_GET_response, "Id") is not None
    assert skyramp.get_response_value(orders_order_id_GET_response, "Name") is not None
    assert skyramp.get_response_value(orders_order_id_GET_response, "Account__c") is not None
    assert skyramp.get_response_value(orders_order_id_GET_response, "CreatedDate") is not None
    assert skyramp.get_response_value(orders_order_id_GET_response, "LastModifiedDate") is not None
    assert skyramp.get_response_value(orders_order_id_GET_response, "Status__c") is not None


if __name__ == "__main__":
    test_orders_order_id_get()
