# Generated by Skyramp v1.3.19 on 2026-05-04 17:24:47.585839 -0400 EDT m=+0.342225209
# Command: skyramp generate contract rest https://playful-bear-m8hbtf-dev-ed.trailblaze.my.salesforce.com/services/data/v65.0/sobjects/Order_Item__c/ \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output-dir /Users/koljaheck/Documents/Professional/Skyramp/Wipro/ebikes-lwc/tests \
# 		--overwrite \
# 		--provider \
# 		--provider-output contract_sobject_order_item_post.py \
# 		--request-data {"Order__c":"PARENT_ORDER_ID","Product__c":"a03g800000ADlWkAAL","Price__c":2999,"Qty_S__c":5,"Qty_M__c":3,"Qty_L__c":2} \
# 		--response-data {"id":"a00FAKE000001","success":true,"errors":[]} \
# 		--response-status-code 201 \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "https://playful-bear-m8hbtf-dev-ed.trailblaze.my.salesforce.com")

# contract test for /services/data/v65.0/sobjects/Order_Item__c/ POST
def test_order_item__c_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Setup: create parent order
    setup_order_body = r'''{
        "Account__c": "001g800000C3eLNAAZ",
        "Status__c": "Draft"
    }'''
    setup_order_response = client.send_request(
        url=URL,
        path="/services/apexrest/orders/",
        method="POST",
        body=setup_order_body,
        headers=headers
    )
    assert setup_order_response.status_code == 201
    parent_order_id = skyramp.get_response_value(setup_order_response, "Id")

    # Request Body
    import json
    Order_Item_c_POST_request_body = json.dumps({
        "Order__c": parent_order_id,
        "Product__c": "a03g800000ADlWkAAL",
        "Price__c": 2999,
        "Qty_S__c": 5,
        "Qty_M__c": 3,
        "Qty_L__c": 2
    })

    # Expected Response Body
    expected_Order_Item_c_POST_response_body = r'''{
        "errors": [],
        "id": "a00FAKE000001",
        "success": true
    }'''

    # Execute Request
    Order_Item_c_POST_response = client.send_request(
        url=URL,
        path="/services/data/v65.0/sobjects/Order_Item__c/",
        method="POST",
        body=Order_Item_c_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert Order_Item_c_POST_response.status_code == 201
    assert skyramp.check_schema(Order_Item_c_POST_response, expected_Order_Item_c_POST_response_body)
    assert skyramp.get_response_value(Order_Item_c_POST_response, "id") is not None
    assert skyramp.get_response_value(Order_Item_c_POST_response, "success") == True


if __name__ == "__main__":
    test_order_item__c_post()
