# Generated by Skyramp v1.3.19 on 2026-04-23 16:51:06.840978 -0400 EDT m=+2946.915048251
# Command: skyramp generate contract rest https://playful-bear-m8hbtf-dev-ed.trailblaze.my.salesforce.com/services/apexrest/order-items/ \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output contract_order_items_post.py \
# 		--output-dir /Users/koljaheck/Documents/Professional/Skyramp/ebikes-lwc/tests \
# 		--overwrite \
# 		--provider \
# 		--request-data {"Order__c":"PARENT_ORDER_ID","Product__c":"a03g800000ADlWkAAL","Price__c":2999,"Qty_S__c":5,"Qty_M__c":3,"Qty_L__c":2} \
# 		--response-data {"Id":"a00FAKE000001","Name":"OI-00001","Order__c":"PARENT_ORDER_ID","Product__c":"a03g800000ADlWkAAL","Price__c":2999,"Qty_S__c":5,"Qty_M__c":3,"Qty_L__c":2} \
# 		--response-status-code 201 \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "https://playful-bear-m8hbtf-dev-ed.trailblaze.my.salesforce.com")

# contract test for /services/apexrest/order-items/ POST
def test_order_items_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Setup: create parent order
    setup_order_body = r'''{
        "Account__c": "001g800000C3eLNAAZ",
        "Status__c": "Draft"
    }'''
    setup_order_response = client.send_request(
        url=URL,
        path="/services/apexrest/orders/",
        method="POST",
        body=setup_order_body,
        headers=headers
    )
    assert setup_order_response.status_code == 201
    parent_order_id = skyramp.get_response_value(setup_order_response, "Id")

    # Request Body
    import json
    order_items_POST_request_body = json.dumps({
        "Order__c": parent_order_id,
        "Product__c": "a03g800000ADlWkAAL",
        "Price__c": 2999,
        "Qty_S__c": 5,
        "Qty_M__c": 3,
        "Qty_L__c": 2
    })

    # Expected Response Body
    expected_order_items_POST_response_body = r'''{
        "Id": "a00FAKE000001",
        "Name": "OI-00001",
        "Order__c": "PARENT_ORDER_ID",
        "Price__c": 2999,
        "Product__c": "a03g800000ADlWkAAL",
        "Qty_L__c": 2,
        "Qty_M__c": 3,
        "Qty_S__c": 5
    }'''

    # Execute Request
    order_items_POST_response = client.send_request(
        url=URL,
        path="/services/apexrest/order-items/",
        method="POST",
        body=order_items_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert order_items_POST_response.status_code == 201
    assert skyramp.get_response_value(order_items_POST_response, "Id") is not None
    assert skyramp.get_response_value(order_items_POST_response, "Name") is not None
    assert skyramp.get_response_value(order_items_POST_response, "Order__c") == parent_order_id
    assert skyramp.get_response_value(order_items_POST_response, "Product__c") == "a03g800000ADlWkAAL"
    assert skyramp.get_response_value(order_items_POST_response, "Price__c") == 2999
    assert skyramp.get_response_value(order_items_POST_response, "Price__c") >= 0
    assert skyramp.get_response_value(order_items_POST_response, "Qty_S__c") == 5
    assert skyramp.get_response_value(order_items_POST_response, "Qty_M__c") == 3
    assert skyramp.get_response_value(order_items_POST_response, "Qty_L__c") == 2

    # Cleanup: delete order item then parent order
    item_id = skyramp.get_response_value(order_items_POST_response, "Id")
    # client.send_request(
    #     url=URL,
    #     path=f"/services/apexrest/order-items/{item_id}",
    #     method="DELETE",
    #     headers=headers
    # )
    # client.send_request(
    #     url=URL,
    #     path=f"/services/apexrest/orders/{parent_order_id}",
    #     method="DELETE",
    #     headers=headers
    # )


if __name__ == "__main__":
    test_order_items_post()
