# Generated by Skyramp v1.3.19 on 2026-04-23 16:54:53.195442 -0400 EDT m=+3173.271703751
# Command: skyramp generate contract rest https://playful-bear-m8hbtf-dev-ed.trailblaze.my.salesforce.com/services/data/v65.0/sobjects/Order__c/describe \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output contract_sobject_order_describe.py \
# 		--output-dir /Users/koljaheck/Documents/Professional/Skyramp/ebikes-lwc/tests \
# 		--overwrite \
# 		--provider \
# 		--response-data {"name":"Order__c","label":"Reseller Order","fields":[{"name":"Account__c","type":"reference","nillable":false},{"name":"Status__c","type":"picklist","nillable":false}]} \
# 		--response-status-code 200 \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "https://playful-bear-m8hbtf-dev-ed.trailblaze.my.salesforce.com")

# contract test for /services/data/v65.0/sobjects/Order__c/describe GET
def test_describe_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Expected Response Body
    expected_describe_GET_response_body = r'''{
        "fields": [
            {
                "name": "Account__c",
                "nillable": false,
                "type": "reference"
            },
            {
                "name": "Status__c",
                "nillable": false,
                "type": "picklist"
            }
        ],
        "label": "Reseller Order",
        "name": "Order__c"
    }'''

    # Execute Request
    describe_GET_response = client.send_request(
        url=URL,
        path="/services/data/v65.0/sobjects/Order__c/describe",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert describe_GET_response.status_code == 200
    assert skyramp.check_schema(describe_GET_response, expected_describe_GET_response_body)
    assert skyramp.get_response_value(describe_GET_response, "name") == "Order__c"
    assert skyramp.get_response_value(describe_GET_response, "label") == "Reseller Order"
    assert skyramp.get_response_value(describe_GET_response, "fields") is not None


if __name__ == "__main__":
    test_describe_get()
