# Generated by Skyramp v1.3.19 on 2026-04-23 16:49:58.984595 -0400 EDT m=+2879.058008168
# Command: skyramp generate contract rest https://playful-bear-m8hbtf-dev-ed.trailblaze.my.salesforce.com/services/apexrest/products/ \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output contract_products_post.py \
# 		--output-dir /Users/koljaheck/Documents/Professional/Skyramp/ebikes-lwc/tests \
# 		--overwrite \
# 		--provider \
# 		--request-data {"Name":"Contract Test Bike","MSRP__c":1999,"Category__c":"Mountain","Material__c":"Carbon","Level__c":"Enthusiast","Description__c":"A test product for contract validation","Picture_URL__c":"https://example.com/bike.png"} \
# 		--response-data {"Id":"a03FAKE000001","Name":"Contract Test Bike","MSRP__c":1999,"Category__c":"Mountain","Material__c":"Carbon","Level__c":"Enthusiast","Description__c":"A test product for contract validation","Picture_URL__c":"https://example.com/bike.png"} \
# 		--response-status-code 201 \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "https://playful-bear-m8hbtf-dev-ed.trailblaze.my.salesforce.com")

# contract test for /services/apexrest/products/ POST
def test_products_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    products_POST_request_body = r'''{
        "Category__c": "Mountain",
        "Description__c": "A test product for contract validation",
        "Level__c": "Enthusiast",
        "MSRP__c": 1999,
        "Material__c": "Carbon",
        "Name": "Contract Test Bike",
        "Picture_URL__c": "https://example.com/bike.png"
    }'''

    # Expected Response Body
    expected_products_POST_response_body = r'''{
        "Category__c": "Mountain",
        "Description__c": "A test product for contract validation",
        "Id": "a03FAKE000001",
        "Level__c": "Enthusiast",
        "MSRP__c": 1999,
        "Material__c": "Carbon",
        "Name": "Contract Test Bike",
        "Picture_URL__c": "https://example.com/bike.png"
    }'''

    # Execute Request
    products_POST_response = client.send_request(
        url=URL,
        path="/services/apexrest/products/",
        method="POST",
        body=products_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert products_POST_response.status_code == 201
    assert skyramp.check_schema(products_POST_response, expected_products_POST_response_body)
    assert skyramp.get_response_value(products_POST_response, "Id") is not None
    assert skyramp.get_response_value(products_POST_response, "Name") == "Contract Test Bike"
    assert skyramp.get_response_value(products_POST_response, "MSRP__c") == 1999
    assert skyramp.get_response_value(products_POST_response, "Category__c") == "Mountain"
    assert skyramp.get_response_value(products_POST_response, "Material__c") == "Carbon"
    assert skyramp.get_response_value(products_POST_response, "Level__c") == "Enthusiast"
    assert skyramp.get_response_value(products_POST_response, "Description__c") == "A test product for contract validation"
    assert skyramp.get_response_value(products_POST_response, "Picture_URL__c") == "https://example.com/bike.png"

    # Cleanup: delete the created product
    product_id = skyramp.get_response_value(products_POST_response, "Id")
    client.send_request(
        url=URL,
        path=f"/services/apexrest/products/{product_id}",
        method="DELETE",
        headers=headers
    )


if __name__ == "__main__":
    test_products_post()
