# Generated by Skyramp v1.3.19 on 2026-04-23 16:54:52.524425 -0400 EDT m=+3172.600679501
# Command: skyramp generate contract rest https://playful-bear-m8hbtf-dev-ed.trailblaze.my.salesforce.com/services/data/v65.0/sobjects/Order__c/ \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output contract_sobject_order_post.py \
# 		--output-dir /Users/koljaheck/Documents/Professional/Skyramp/ebikes-lwc/tests \
# 		--overwrite \
# 		--provider \
# 		--request-data {"Account__c":"001g800000C3eLNAAZ","Status__c":"Draft"} \
# 		--response-data {"id":"a01FAKE000001","success":true,"errors":[]} \
# 		--response-status-code 201 \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "https://playful-bear-m8hbtf-dev-ed.trailblaze.my.salesforce.com")

# contract test for /services/data/v65.0/sobjects/Order__c/ POST
def test_order__c_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    Order_c_POST_request_body = r'''{
        "Account__c": "001g800000C3eLNAAZ",
        "Status__c": "Draft"
    }'''

    # Expected Response Body
    expected_Order_c_POST_response_body = r'''{
        "errors": [],
        "id": "a01FAKE000001",
        "success": true
    }'''

    # Execute Request
    Order_c_POST_response = client.send_request(
        url=URL,
        path="/services/data/v65.0/sobjects/Order__c/",
        method="POST",
        body=Order_c_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert Order_c_POST_response.status_code == 201
    assert skyramp.check_schema(Order_c_POST_response, expected_Order_c_POST_response_body)
    assert skyramp.get_response_value(Order_c_POST_response, "id") is not None
    assert skyramp.get_response_value(Order_c_POST_response, "success") == True

    # Cleanup: delete the created order
    order_id = skyramp.get_response_value(Order_c_POST_response, "id")
    client.send_request(
        url=URL,
        path=f"/services/data/v65.0/sobjects/Order__c/{order_id}",
        method="DELETE",
        headers=headers
    )


if __name__ == "__main__":
    test_order__c_post()
