# Generated by Skyramp v1.3.18 on 2026-04-24 17:02:01.525347062 +0000 UTC m=+310.603587194
# Command: skyramp generate contract rest https://playful-bear-m8hbtf-dev-ed.trailblaze.my.salesforce.com/services/apexrest/orders/{orders_id} \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output contract_orders_get.py \
# 		--output-dir /home/runner/work/ebikes-lwc/ebikes-lwc/tests \
# 		--overwrite \
# 		--path-params orders_id=a01g800000ADlWpAAL \
# 		--provider \
# 		--response-data {"Id":"a01FAKE000001","Name":"O-00001","Status__c":"Draft","Account__c":"001g800000C3eLNAAZ","Discount_Percent__c":15} \
# 		--response-status-code 200 \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "https://playful-bear-m8hbtf-dev-ed.trailblaze.my.salesforce.com")

# contract test for /services/apexrest/orders/{orders_id} GET
def test_orders_orders_id_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Setup: create parent order to GET
    setup_order_body = r'''{
        "Account__c": "001g800000C3eLNAAZ",
        "Status__c": "Draft",
        "Discount_Percent__c": 15
    }'''
    setup_response = client.send_request(
        url=URL,
        path="/services/apexrest/orders/",
        method="POST",
        body=setup_order_body,
        headers=headers
    )
    assert setup_response.status_code == 201
    orders_id = skyramp.get_response_value(setup_response, "Id")

    # Expected Response Body
    expected_orders_orders_id_GET_response_body = r'''{
        "Account__c": "001g800000C3eLNAAZ",
        "Discount_Percent__c": 15,
        "Id": "a01FAKE000001",
        "Name": "O-00001",
        "Status__c": "Draft"
    }'''

    # Execute Request
    orders_orders_id_GET_response = client.send_request(
        url=URL,
        path="/services/apexrest/orders/{orders_id}",
        method="GET",
        headers=headers,
        path_params={"orders_id": orders_id}
    )

    # Generated Assertions
    assert orders_orders_id_GET_response.status_code == 200
    assert skyramp.check_schema(orders_orders_id_GET_response, expected_orders_orders_id_GET_response_body)
    assert skyramp.get_response_value(orders_orders_id_GET_response, "Account__c") is not None
    assert skyramp.get_response_value(orders_orders_id_GET_response, "Discount_Percent__c") is not None
    assert skyramp.get_response_value(orders_orders_id_GET_response, "Id") is not None
    assert skyramp.get_response_value(orders_orders_id_GET_response, "Name") is not None
    assert skyramp.get_response_value(orders_orders_id_GET_response, "Status__c") is not None
    assert skyramp.get_response_value(orders_orders_id_GET_response, "Discount_Percent__c") >= 0

    # Cleanup: delete the created order
    client.send_request(
        url=URL,
        path=f"/services/apexrest/orders/{orders_id}",
        method="DELETE",
        headers=headers
    )


if __name__ == "__main__":
    test_orders_orders_id_get()
