# Generated by Skyramp v1.3.18 on 2026-04-24 13:54:01.709279224 +0000 UTC m=+21.517615573
# Command: skyramp generate contract rest https://playful-bear-m8hbtf-dev-ed.trailblaze.my.salesforce.com/services/apexrest/orders/{id} \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--method PUT \
# 		--output contract_orders_put.py \
# 		--output-dir /home/runner/work/ebikes-lwc/ebikes-lwc/tests \
# 		--overwrite \
# 		--provider \
# 		--request-data {"Status__c":"Submitted to Manufacturing","Discount_Percent__c":45} \
# 		--response-data {"Id":"a01FAKE000001","Name":"O-00001","Status__c":"Submitted to Manufacturing","Account__c":"001g800000C3eLNAAZ","Discount_Percent__c":45,"CreatedDate":"2026-04-24T00:00:00.000Z"} \
# 		--response-status-code 200 \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "https://playful-bear-m8hbtf-dev-ed.trailblaze.my.salesforce.com")

# contract test for /services/apexrest/orders/{id} PUT
def test_orders_id_put():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Setup: provision a parent order to update
    setup_order_body = r'''{
        "Account__c": "001g800000C3eLNAAZ",
        "Status__c": "Draft",
        "Discount_Percent__c": 20
    }'''
    setup_order_response = client.send_request(
        url=URL,
        path="/services/apexrest/orders/",
        method="POST",
        body=setup_order_body,
        headers=headers
    )
    assert setup_order_response.status_code == 201
    id = skyramp.get_response_value(setup_order_response, "Id")

    # Request Body
    orders_id_PUT_request_body = r'''{
        "Discount_Percent__c": 45,
        "Status__c": "Submitted to Manufacturing"
    }'''

    # Expected Response Body
    expected_orders_id_PUT_response_body = r'''{
        "Account__c": "001g800000C3eLNAAZ",
        "CreatedDate": "2026-04-24T00:00:00.000Z",
        "Discount_Percent__c": 45,
        "Id": "a01FAKE000001",
        "Name": "O-00001",
        "Status__c": "Submitted to Manufacturing"
    }'''

    # Execute Request
    orders_id_PUT_response = client.send_request(
        url=URL,
        path="/services/apexrest/orders/{id}",
        method="PUT",
        body=orders_id_PUT_request_body,
        headers=headers,
        path_params={"id": id}
    )

    # Generated Assertions
    assert orders_id_PUT_response.status_code == 200
    assert skyramp.check_schema(orders_id_PUT_response, expected_orders_id_PUT_response_body)
    assert skyramp.get_response_value(orders_id_PUT_response, "Id") is not None
    assert skyramp.get_response_value(orders_id_PUT_response, "Account__c") is not None
    assert skyramp.get_response_value(orders_id_PUT_response, "CreatedDate") is not None
    assert skyramp.get_response_value(orders_id_PUT_response, "Status__c") == "Submitted to Manufacturing"
    assert skyramp.get_response_value(orders_id_PUT_response, "Discount_Percent__c") == 45

    # Cleanup: delete the provisioned order
    client.send_request(
        url=URL,
        path=f"/services/apexrest/orders/{id}",
        method="DELETE",
        headers=headers
    )


if __name__ == "__main__":
    test_orders_id_put()
