# Generated by Skyramp v1.3.18 on 2026-04-24 18:57:45.846286814 +0000 UTC m=+184.445816187
# Command: skyramp generate contract rest https://playful-bear-m8hbtf-dev-ed.trailblaze.my.salesforce.com/services/apexrest/products/ \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output contract_products_post.py \
# 		--output-dir /home/runner/work/ebikes-lwc/ebikes-lwc/tests \
# 		--overwrite \
# 		--provider \
# 		--request-data {"Name":"Test E-Bike Rating","MSRP__c":1299.99,"Category__c":"Mountain","Level__c":"Beginner","Rating__c":4.5} \
# 		--response-data {"Id":"a000000000001AAAA","Name":"Test E-Bike Rating","MSRP__c":1299.99,"Category__c":"Mountain","Level__c":"Beginner","Rating__c":4.5} \
# 		--response-status-code 201 \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "https://playful-bear-m8hbtf-dev-ed.trailblaze.my.salesforce.com")

# contract test for /services/apexrest/products/ POST
def test_products_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    products_POST_request_body = r'''{
        "Category__c": "Mountain",
        "Level__c": "Beginner",
        "MSRP__c": 1299.99,
        "Name": "Test E-Bike Rating",
        "Rating__c": 4.5
    }'''

    # Expected Response Body
    expected_products_POST_response_body = r'''{
        "Category__c": "Mountain",
        "Id": "a000000000001AAAA",
        "Level__c": "Beginner",
        "MSRP__c": 1299.99,
        "Name": "Test E-Bike Rating",
        "Rating__c": 4.5
    }'''

    # Execute Request
    products_POST_response = client.send_request(
        url=URL,
        path="/services/apexrest/products/",
        method="POST",
        body=products_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert products_POST_response.status_code == 201
    assert skyramp.check_schema(products_POST_response, expected_products_POST_response_body)
    assert skyramp.get_response_value(products_POST_response, "Category__c") is not None
    assert skyramp.get_response_value(products_POST_response, "Id") is not None
    assert skyramp.get_response_value(products_POST_response, "Level__c") is not None
    assert skyramp.get_response_value(products_POST_response, "Name") == "Test E-Bike Rating"
    assert skyramp.get_response_value(products_POST_response, "MSRP__c") == 1299.99
    assert skyramp.get_response_value(products_POST_response, "Rating__c") == 4.5
    assert skyramp.get_response_value(products_POST_response, "MSRP__c") >= 0
    assert skyramp.get_response_value(products_POST_response, "Rating__c") >= 0
    assert skyramp.get_response_value(products_POST_response, "Rating__c") <= 5

    # Cleanup: delete the created product
    product_id = skyramp.get_response_value(products_POST_response, "Id")
    client.send_request(
        url=URL,
        path=f"/services/apexrest/products/{product_id}",
        method="DELETE",
        headers=headers
    )


if __name__ == "__main__":
    test_products_post()
