# Generated by Skyramp v1.3.18 on 2026-04-24 19:09:15.951765309 +0000 UTC m=+250.780422182
# Command: skyramp generate contract rest https://playful-bear-m8hbtf-dev-ed.trailblaze.my.salesforce.com/services/apexrest/orders/{order_id} \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output contract_orders_get.py \
# 		--output-dir /home/runner/work/ebikes-lwc/ebikes-lwc/tests \
# 		--overwrite \
# 		--path-params order_id=a01FAKE000001 \
# 		--provider \
# 		--response-data {"Id":"a01FAKE000001","Name":"O-00043","Status__c":"Draft","Account__c":"001g800000C3eLNAAZ","CreatedDate":"2026-04-24T00:00:00.000Z","LastModifiedDate":"2026-04-24T00:00:00.000Z"} \
# 		--response-status-code 200 \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "https://playful-bear-m8hbtf-dev-ed.trailblaze.my.salesforce.com")

# contract test for /services/apexrest/orders/{order_id} GET
def test_orders_order_id_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Setup: create an order to retrieve
    setup_order_body = r'''{
        "Account__c": "001g800000C3eLNAAZ",
        "Status__c": "Draft"
    }'''
    setup_order_response = client.send_request(
        url=URL,
        path="/services/apexrest/orders/",
        method="POST",
        body=setup_order_body,
        headers=headers
    )
    assert setup_order_response.status_code == 201
    order_id = skyramp.get_response_value(setup_order_response, "Id")

    # Expected Response Body
    expected_orders_order_id_GET_response_body = r'''{
        "Account__c": "001g800000C3eLNAAZ",
        "CreatedDate": "2026-04-24T00:00:00.000Z",
        "Id": "a01FAKE000001",
        "LastModifiedDate": "2026-04-24T00:00:00.000Z",
        "Name": "O-00043",
        "Status__c": "Draft"
    }'''

    # Execute Request
    orders_order_id_GET_response = client.send_request(
        url=URL,
        path="/services/apexrest/orders/{order_id}",
        method="GET",
        headers=headers,
        path_params={"order_id": order_id}
    )

    # Generated Assertions
    assert orders_order_id_GET_response.status_code == 200
    assert skyramp.check_schema(orders_order_id_GET_response, expected_orders_order_id_GET_response_body)
    assert skyramp.get_response_value(orders_order_id_GET_response, "Id") is not None
    assert skyramp.get_response_value(orders_order_id_GET_response, "Name") is not None
    assert skyramp.get_response_value(orders_order_id_GET_response, "Account__c") == "001g800000C3eLNAAZ"
    assert skyramp.get_response_value(orders_order_id_GET_response, "Status__c") == "Draft"
    assert skyramp.get_response_value(orders_order_id_GET_response, "CreatedDate") is not None
    assert skyramp.get_response_value(orders_order_id_GET_response, "LastModifiedDate") is not None

    # Cleanup: delete the created order
    client.send_request(
        url=URL,
        path=f"/services/apexrest/orders/{order_id}",
        method="DELETE",
        headers=headers
    )


if __name__ == "__main__":
    test_orders_order_id_get()
