# Generated by Skyramp v1.3.19 on 2026-04-23 16:50:31.547944 -0400 EDT m=+2911.621672460
# Command: skyramp generate contract rest https://playful-bear-m8hbtf-dev-ed.trailblaze.my.salesforce.com/services/apexrest/orders/ \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output contract_orders_post.py \
# 		--output-dir /Users/koljaheck/Documents/Professional/Skyramp/ebikes-lwc/tests \
# 		--overwrite \
# 		--provider \
# 		--request-data {"Account__c":"001g800000C3eLNAAZ","Status__c":"Draft"} \
# 		--response-data {"Id":"a01FAKE000001","Name":"O-00099","Status__c":"Draft","Account__c":"001g800000C3eLNAAZ","CreatedDate":"2026-04-23T20:00:00.000Z"} \
# 		--response-status-code 201 \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "https://playful-bear-m8hbtf-dev-ed.trailblaze.my.salesforce.com")

# contract test for /services/apexrest/orders/ POST
def test_orders_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    orders_POST_request_body = r'''{
        "Account__c": "001g800000C3eLNAAZ",
        "Status__c": "Draft",
        "Discount_Percent__c": 15.5
    }'''

    # Expected Response Body
    expected_orders_POST_response_body = r'''{
        "Account__c": "001g800000C3eLNAAZ",
        "CreatedDate": "2026-04-23T20:00:00.000Z",
        "Discount_Percent__c": 15.5,
        "Id": "a01FAKE000001",
        "Name": "O-00099",
        "Status__c": "Draft"
    }'''

    # Execute Request
    orders_POST_response = client.send_request(
        url=URL,
        path="/services/apexrest/orders/",
        method="POST",
        body=orders_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert orders_POST_response.status_code == 201
    assert skyramp.check_schema(orders_POST_response, expected_orders_POST_response_body)
    assert skyramp.get_response_value(orders_POST_response, "Id") is not None
    assert skyramp.get_response_value(orders_POST_response, "Name") is not None
    assert skyramp.get_response_value(orders_POST_response, "Account__c") == "001g800000C3eLNAAZ"
    assert skyramp.get_response_value(orders_POST_response, "Status__c") == "Draft"
    assert skyramp.get_response_value(orders_POST_response, "CreatedDate") is not None
    assert skyramp.get_response_value(orders_POST_response, "Discount_Percent__c") == 15.5
    assert skyramp.get_response_value(orders_POST_response, "Discount_Percent__c") >= 0

    # Cleanup: delete the created order
    order_id = skyramp.get_response_value(orders_POST_response, "Id")
    client.send_request(
        url=URL,
        path=f"/services/apexrest/orders/{order_id}",
        method="DELETE",
        headers=headers
    )


def test_orders_put():
    client = skyramp.Client()
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    setup_body = r'''{
        "Account__c": "001g800000C3eLNAAZ",
        "Status__c": "Draft",
        "Discount_Percent__c": 10.0
    }'''
    setup_response = client.send_request(
        url=URL,
        path="/services/apexrest/orders/",
        method="POST",
        body=setup_body,
        headers=headers
    )
    assert setup_response.status_code == 201
    order_id = skyramp.get_response_value(setup_response, "Id")

    orders_PUT_request_body = r'''{
        "Status__c": "Submitted to Manufacturing",
        "Discount_Percent__c": 30.0
    }'''

    expected_orders_PUT_response_body = r'''{
        "Account__c": "001g800000C3eLNAAZ",
        "Discount_Percent__c": 30.0,
        "Id": "a01FAKE000001",
        "Name": "O-00099",
        "Status__c": "Submitted to Manufacturing"
    }'''

    orders_PUT_response = client.send_request(
        url=URL,
        path=f"/services/apexrest/orders/{order_id}",
        method="PUT",
        body=orders_PUT_request_body,
        headers=headers
    )

    assert orders_PUT_response.status_code == 200
    assert skyramp.check_schema(orders_PUT_response, expected_orders_PUT_response_body)
    assert skyramp.get_response_value(orders_PUT_response, "Id") is not None
    assert skyramp.get_response_value(orders_PUT_response, "Name") is not None
    assert skyramp.get_response_value(orders_PUT_response, "Account__c") == "001g800000C3eLNAAZ"
    assert skyramp.get_response_value(orders_PUT_response, "Status__c") == "Submitted to Manufacturing"
    assert skyramp.get_response_value(orders_PUT_response, "Discount_Percent__c") == 30.0
    assert skyramp.get_response_value(orders_PUT_response, "Discount_Percent__c") >= 0

    client.send_request(
        url=URL,
        path=f"/services/apexrest/orders/{order_id}",
        method="DELETE",
        headers=headers
    )


if __name__ == "__main__":
    test_orders_post()
    test_orders_put()
