# Generated by Skyramp v1.3.18 on 2026-04-24 15:32:00.85426021 +0000 UTC m=+128.203943695
# Command: skyramp generate contract rest https://playful-bear-m8hbtf-dev-ed.trailblaze.my.salesforce.com/services/apexrest/orders/{orders_id} \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--method PUT \
# 		--output contract_orders_put_discount.py \
# 		--output-dir /home/runner/work/ebikes-lwc/ebikes-lwc/tests \
# 		--overwrite \
# 		--path-params orders_id=a01g800000ADlWpAAL \
# 		--provider \
# 		--request-data {"Discount_Percent__c":30,"Status__c":"Draft"} \
# 		--response-data {"Id":"a01FAKE000001","Name":"O-00001","Status__c":"Draft","Account__c":"001g800000C3eLNAAZ","Discount_Percent__c":30} \
# 		--response-status-code 200 \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "https://playful-bear-m8hbtf-dev-ed.trailblaze.my.salesforce.com")

# contract test for /services/apexrest/orders/{orders_id} PUT
def test_orders_orders_id_put():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    orders_id = "a01g800000ADlWpAAL"

    # Request Body
    orders_orders_id_PUT_request_body = r'''{
        "Discount_Percent__c": 30,
        "Status__c": "Draft"
    }'''

    # Expected Response Body
    expected_orders_orders_id_PUT_response_body = r'''{
        "Account__c": "001g800000C3eLNAAZ",
        "Discount_Percent__c": 30,
        "Id": "a01FAKE000001",
        "Name": "O-00001",
        "Status__c": "Draft"
    }'''

    # Execute Request
    orders_orders_id_PUT_response = client.send_request(
        url=URL,
        path="/services/apexrest/orders/{orders_id}",
        method="PUT",
        body=orders_orders_id_PUT_request_body,
        headers=headers,
        path_params={"orders_id": orders_id}
    )

    # Generated Assertions
    assert orders_orders_id_PUT_response.status_code == 200
    assert skyramp.check_schema(orders_orders_id_PUT_response, expected_orders_orders_id_PUT_response_body)
    assert skyramp.get_response_value(orders_orders_id_PUT_response, "Account__c") is not None
    assert skyramp.get_response_value(orders_orders_id_PUT_response, "Discount_Percent__c") is not None
    assert skyramp.get_response_value(orders_orders_id_PUT_response, "Id") is not None
    assert skyramp.get_response_value(orders_orders_id_PUT_response, "Discount_Percent__c") == 30
    assert skyramp.get_response_value(orders_orders_id_PUT_response, "Discount_Percent__c") >= 0
    assert skyramp.get_response_value(orders_orders_id_PUT_response, "Status__c") == "Draft"


if __name__ == "__main__":
    test_orders_orders_id_put()
