// Generated by Skyramp v1.3.23 on 2026-05-04 15:13:20.240367 -0400 EDT m=+7575.632263501
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output-dir /Users/koljaheck/Documents/Professional/Skyramp/Wipro/ebikes-lwc/tests \
// 		--overwrite \
// 		--playwright-trace /Users/koljaheck/Documents/Professional/Skyramp/Wipro/ebikes-lwc/skyramp_playwright.zip

// Import of required libraries
import { test, Page } from '@playwright/test';
import { expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    storageState: '/Users/koljaheck/Documents/Professional/Skyramp/Wipro/ebikes-lwc/skyramp_session.json',
});

async function verifyOrderState(page: Page, totalItems: string, orderTotal: string) {
    await expect(page.locator("c-order-builder")).toContainText(`Total Items: ${totalItems}`);
    await expect(page.locator("c-order-builder")).toContainText(`Order Total:${orderTotal}`);
}

async function addItemsToOrderByDrag(page: Page) {
    // Mouse scrolling block
    await page.waitForTimeout(3000);
    await page.mouse.move(581, 313);
    await page.mouse.move(581, 312);
    await page.mouse.move(581, 311);
    await page.mouse.move(581, 310);
    await page.mouse.wheel(0, 118);
    await expect(page.locator("c-order-builder")).toContainText("Total Items: 0");
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise1 = page.waitForResponse("**/aura**");
    await page.locator("one-record-home-flexipage2").dragTo(
        page.locator("one-record-home-flexipage2"),
        {
            sourcePosition: {"x": 1050, "y": 259},
            targetPosition: {"x": 444, "y": 619}
        }
    );
    const response1 = await responsePromise1;

    // Assert network response
    expect(response1.status()).toBe(200);

    // Mouse scrolling block
    await page.waitForTimeout(3000);
    await page.mouse.move(537, 538);
    await page.mouse.wheel(0, 148);
}

async function clearOrderItems(page: Page) {
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise3 = page.waitForResponse("**/aura**");
    await page.locator("#tab-3").getByRole("button").filter({ hasText: /^$/ }).click();
    const response3 = await responsePromise3;

    // Assert network response
    expect(response3.status()).toBe(200);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);
}

test('testUi', async ({ page }) => {
    test.setTimeout(256000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    // Register page error handler
    const errors: Error[] = [];
    page.on('pageerror', (error) => errors.push(error));

    await page.goto("https://playful-bear-m8hbtf-dev-ed.trailblaze.lightning.force.com/lightning/page/home");
    // Wait for network activities to finish
    await page.waitForTimeout(2250);

    await page.getByRole("link", { name: "Reseller Orders" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    const responsePromise0 = page.waitForResponse("**/aura**");
    await page.getByRole("link", { name: "O-00083" }).click();
    const response0 = await responsePromise0;

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    // Assert network response
    expect(response0.status()).toBe(200);

    await addItemsToOrderByDrag(page);
    await verifyOrderState(page, "3", "$12,600.00");

    await page.getByText("DYNAMO X1MSRP:$7,000.00PriceSmallMediumLarge", { exact: true }).hover();

    await clearOrderItems(page);
    await verifyOrderState(page, "0", "$0.00");

    // Assert no page errors occurred
    expect(errors).toHaveLength(0);
});
