// Generated by Skyramp v1.3.23 on 2026-05-04 16:08:07.547327 -0400 EDT m=+10862.924218084
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output-dir /Users/koljaheck/Documents/Professional/Skyramp/Wipro/ebikes-lwc/tests \
// 		--overwrite \
// 		--playwright-trace /Users/koljaheck/Documents/Professional/Skyramp/Wipro/ebikes-lwc/skyramp_playwright.zip

// Import of required libraries
import { test, Page } from '@playwright/test';
import { expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    storageState: '/Users/koljaheck/Documents/Professional/Skyramp/Wipro/ebikes-lwc/skyramp_session.json',
});

async function dragPriceSlider(page: Page) {
    await page.locator(".slds-col--padded.slds-size--12-of-12.slds-medium-size--3-of-12 > div > .ui-widget").first().dragTo(
        page.locator("c-product-filter"),
        {
            sourcePosition: {"x": 212, "y": 175},
            targetPosition: {"x": 140, "y": 180}
        }
    );
    await expect(page.locator("c-product-tile-list")).toHaveScreenshot("el-002.png", { maxDiffPixelRatio: 0.005 });
}

async function applyFilter(page: Page) {
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise2 = page.waitForResponse("**/ebikes/s/sfsites/aura**");
    await page.locator(".slds-checkbox_faux").first().click();
    const response2 = await responsePromise2;

    // Assert network response
    expect(response2.status()).toBe(200);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);
}

test('testUi', async ({ page }, testInfo) => {
    test.setTimeout(1218000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page, testInfo);

    // Register page error handler
    const errors: Error[] = [];
    page.on('pageerror', (error) => errors.push(error));

    await page.goto("https://playful-bear-m8hbtf-dev-ed.trailblaze.my.site.com/ebikes/s/product-explorer");
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await expect(page.locator("c-product-tile-list")).toHaveScreenshot("el-001.png", { maxDiffPixelRatio: 0.005 });

    await dragPriceSlider(page);

    await applyFilter(page);

    await expect(page.locator("c-product-tile-list")).toHaveScreenshot("el-003.png", { maxDiffPixelRatio: 0.005 });

    // Assert no page errors occurred
    expect(errors).toHaveLength(0);
});
