# Generated by Skyramp v1.3.18 on 2026-04-24 17:02:05.045451394 +0000 UTC m=+314.123691526
# Command: skyramp generate fuzz rest https://playful-bear-m8hbtf-dev-ed.trailblaze.my.salesforce.com/services/apexrest/orders/ \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output fuzz_orders_discount.py \
# 		--output-dir /home/runner/work/ebikes-lwc/ebikes-lwc/tests \
# 		--overwrite \
# 		--request-data {"Account__c":"001g800000C3eLNAAZ","Status__c":"Draft","Discount_Percent__c":0} \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "https://playful-bear-m8hbtf-dev-ed.trailblaze.my.salesforce.com")

# fuzz test for /services/apexrest/orders/ POST
def test_orders_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    orders_POST_request_body = r'''{
      "Account__c": "001g800000C3eLNAAZ",
      "Status__c": "Draft",
      "Discount_Percent__c": 0
    }'''
    
    # Fuzz strategies
    orders_post_fuzzed_body = {
        "Account__c": "0123456789",
        "Discount_Percent__c": -10,
        "Status__c": "0123456789"
    }
    # Fuzz status codes
    expected_orders_post_status_code = {
        "Account__c": "40x",
        "Discount_Percent__c": "40x",
        "Status__c": "40x"
    }
    # Fuzz status codes for Null values
    expected_orders_post_null_status_code = {
        "Account__c": "40x",
        "Discount_Percent__c": "40x",
        "Status__c": "40x"
    }

    # Execute Request
    orders_POST_response = client.send_request(
        url=URL,
        path="/services/apexrest/orders/",
        method="POST",
        body=orders_POST_request_body,
        headers=headers,
        expected_code="20x"
    )

    for key in skyramp.iterate(orders_post_fuzzed_body):
        # Execute Request
        orders_POST_response = client.send_request(
            url=URL,
            path="/services/apexrest/orders/",
            method="POST",
            body=orders_POST_request_body,
            headers=headers,
            data_override={key: skyramp.get_value(orders_post_fuzzed_body, key)},
            expected_code=skyramp.get_value(expected_orders_post_status_code, key),
            description=f'Fuzzing request body { key } to { skyramp.get_value(orders_post_fuzzed_body, key) }'
        )

        # Execute Request
        orders_POST_response = client.send_request(
            url=URL,
            path="/services/apexrest/orders/",
            method="POST",
            body=orders_POST_request_body,
            headers=headers,
            data_override={key: None},
            expected_code=skyramp.get_value(expected_orders_post_null_status_code, key),
            description=f'Fuzzing request body { key } to None'
        )

    assert client.is_success()


if __name__ == "__main__":
    test_orders_post()
