// Generated by Skyramp v1.3.18 on 2026-04-24 19:06:46.121280924 +0000 UTC m=+100.949937807
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output hero_social_proof_ui_test.spec.ts \
// 		--output-dir /home/runner/work/ebikes-lwc/ebikes-lwc/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/ebikes-lwc/ebikes-lwc/.skyramp/hero_social_proof_trace.zip

// Import of required libraries
import { test, expect } from '@playwright/test';
import { newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(60000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const errors: string[] = [];
    page.on('pageerror', (err) => errors.push(err.message));

    await page.goto("https://playful-bear-m8hbtf-dev-ed.trailblaze.my.site.com/ebikes/s/");
    await page.waitForLoadState('networkidle');

    await expect(page.locator('h1:has-text("Dynamo X2")')).toBeVisible();
    await expect(page.locator('h1:has-text("Electra Series")')).toBeVisible();
    await expect(page.locator('text=happy riders')).toBeVisible();

    expect(errors).toHaveLength(0);
});
