# Generated by Skyramp v1.3.18 on 2026-04-24 03:51:03.432284148 +0000 UTC m=+312.049313491
# Command: skyramp generate integration rest \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--output order_items_filter_integration_test.py \
# 		--output-dir /home/runner/work/ebikes-lwc/ebikes-lwc/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/ebikes-lwc/ebikes-lwc/tests/scenario_order-items-filter-by-order.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_playful_bear_m8hbtf_dev_ed = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "https://playful-bear-m8hbtf-dev-ed.trailblaze.my.salesforce.com")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    endpoint_2_POST_request_body = r'''{
        "Account__c": "001g800000C3eLNAAZ",
        "Status__c": "Draft"
    }'''

    # Execute Request
    endpoint_2_POST_response = client.send_request(
        url=URL_playful_bear_m8hbtf_dev_ed,
        path="/services/apexrest/orders/",
        method="POST",
        body=endpoint_2_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_2_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_2_POST_response, "Id") is not None
    assert skyramp.get_response_value(endpoint_2_POST_response, "Account__c") == "001g800000C3eLNAAZ"
    assert skyramp.get_response_value(endpoint_2_POST_response, "Status__c") == "Draft"

    orders = skyramp.get_response_value(endpoint_2_POST_response, "Id")

    import json
    endpoint_1_POST_request_body = json.dumps({
        "Order__c": orders,
        "Price__c": 2999,
        "Product__c": "a03g800000ADlWkAAL",
        "Qty_L__c": 2,
        "Qty_M__c": 3,
        "Qty_S__c": 5
    })

    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_playful_bear_m8hbtf_dev_ed,
        path="/services/apexrest/order-items/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_1_POST_response, "Id") is not None
    assert skyramp.get_response_value(endpoint_1_POST_response, "Order__c") == orders
    assert skyramp.get_response_value(endpoint_1_POST_response, "Product__c") == "a03g800000ADlWkAAL"
    assert skyramp.get_response_value(endpoint_1_POST_response, "Price__c") == 2999
    assert skyramp.get_response_value(endpoint_1_POST_response, "Price__c") >= 0
    assert skyramp.get_response_value(endpoint_1_POST_response, "Qty_S__c") == 5
    assert skyramp.get_response_value(endpoint_1_POST_response, "Qty_M__c") == 3
    assert skyramp.get_response_value(endpoint_1_POST_response, "Qty_L__c") == 2

    order_items = skyramp.get_response_value(endpoint_1_POST_response, "Id")

    # Execute Request
    endpoint_1_GET_response = client.send_request(
        url=URL_playful_bear_m8hbtf_dev_ed,
        path="/services/apexrest/order-items/",
        method="GET",
        headers=headers,
        query_params={"orderId": orders}
    )
    # Generated Assertions
    assert endpoint_1_GET_response.status_code == 200
    assert skyramp.get_response_value(endpoint_1_GET_response, "0.Id") is not None
    assert skyramp.get_response_value(endpoint_1_GET_response, "0.Order__c") == orders

    # Execute Request
    order_items_DELETE_response = client.send_request(
        url=URL_playful_bear_m8hbtf_dev_ed,
        path=f"/services/apexrest/order-items/{order_items}",
        method="DELETE",
        headers=headers
    )
    # Generated Assertions
    assert order_items_DELETE_response.status_code == 204

    # Execute Request
    orders_DELETE_response = client.send_request(
        url=URL_playful_bear_m8hbtf_dev_ed,
        path="/services/apexrest/orders/{orders}",
        method="DELETE",
        headers=headers,
        path_params={"orders": orders}
    )
    # Generated Assertions
    assert orders_DELETE_response.status_code == 204


if __name__ == "__main__":
    test_integration()
