# Generated by Skyramp v1.3.19 on 2026-04-23 16:32:20.708637 -0400 EDT m=+1820.740848668
# Command: skyramp generate integration rest \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--output order_lifecycle_integration_test.py \
# 		--output-dir /Users/koljaheck/Documents/Professional/Skyramp/ebikes-lwc/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /Users/koljaheck/Documents/Professional/Skyramp/ebikes-lwc/tests/scenario_order_lifecycle.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_playful_bear_m8hbtf_dev_ed = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "https://playful-bear-m8hbtf-dev-ed.trailblaze.my.salesforce.com")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Step 1: Create a Draft order
    endpoint_1_POST_request_body = r'''{
        "Account__c": "001g800000C3eLNAAZ",
        "Status__c": "Draft"
    }'''

    endpoint_1_POST_response = client.send_request(
        url=URL_playful_bear_m8hbtf_dev_ed,
        path="/services/apexrest/orders/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers=headers
    )
    assert endpoint_1_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_1_POST_response, "Id") is not None
    assert skyramp.get_response_value(endpoint_1_POST_response, "Name") is not None
    assert skyramp.get_response_value(endpoint_1_POST_response, "Status__c") == "Draft"
    assert skyramp.get_response_value(endpoint_1_POST_response, "Account__c") == "001g800000C3eLNAAZ"
    assert skyramp.get_response_value(endpoint_1_POST_response, "LastModifiedDate") is not None

    # Chain the order ID for all subsequent requests
    orders = skyramp.get_response_value(endpoint_1_POST_response, "Id")

    # Step 2: Read back the created order
    orders_GET_response = client.send_request(
        url=URL_playful_bear_m8hbtf_dev_ed,
        path="/services/apexrest/orders/{orders}",
        method="GET",
        headers=headers,
        path_params={"orders": orders}
    )
    assert orders_GET_response.status_code == 200
    assert skyramp.get_response_value(orders_GET_response, "Id") == skyramp.get_response_value(endpoint_1_POST_response, "Id")
    assert skyramp.get_response_value(orders_GET_response, "Status__c") == "Draft"
    assert skyramp.get_response_value(orders_GET_response, "Account__c") == "001g800000C3eLNAAZ"
    assert skyramp.get_response_value(orders_GET_response, "LastModifiedDate") is not None

    # Step 3: Update status to Submitted to Manufacturing
    orders_PUT_request_body = r'''{
        "Status__c": "Submitted to Manufacturing"
    }'''

    orders_PUT_response = client.send_request(
        url=URL_playful_bear_m8hbtf_dev_ed,
        path="/services/apexrest/orders/{orders}",
        method="PUT",
        body=orders_PUT_request_body,
        headers=headers,
        path_params={"orders": orders}
    )
    assert orders_PUT_response.status_code == 200
    assert skyramp.get_response_value(orders_PUT_response, "Id") == skyramp.get_response_value(endpoint_1_POST_response, "Id")
    assert skyramp.get_response_value(orders_PUT_response, "Status__c") == "Submitted to Manufacturing"
    assert skyramp.get_response_value(orders_PUT_response, "Account__c") == "001g800000C3eLNAAZ"
    assert skyramp.get_response_value(orders_PUT_response, "LastModifiedDate") is not None

    # Step 4: Verify status persisted
    orders_GET_1_response = client.send_request(
        url=URL_playful_bear_m8hbtf_dev_ed,
        path="/services/apexrest/orders/{orders}",
        method="GET",
        headers=headers,
        path_params={"orders": orders}
    )
    assert orders_GET_1_response.status_code == 200
    assert skyramp.get_response_value(orders_GET_1_response, "Id") == skyramp.get_response_value(endpoint_1_POST_response, "Id")
    assert skyramp.get_response_value(orders_GET_1_response, "Status__c") == "Submitted to Manufacturing"
    assert skyramp.get_response_value(orders_GET_1_response, "LastModifiedDate") is not None

    # Step 5: Update status to Approved by Manufacturing
    orders_PUT_1_request_body = r'''{
        "Status__c": "Approved by Manufacturing"
    }'''

    orders_PUT_1_response = client.send_request(
        url=URL_playful_bear_m8hbtf_dev_ed,
        path="/services/apexrest/orders/{orders}",
        method="PUT",
        body=orders_PUT_1_request_body,
        headers=headers,
        path_params={"orders": orders}
    )
    assert orders_PUT_1_response.status_code == 200
    assert skyramp.get_response_value(orders_PUT_1_response, "Id") == skyramp.get_response_value(endpoint_1_POST_response, "Id")
    assert skyramp.get_response_value(orders_PUT_1_response, "Status__c") == "Approved by Manufacturing"
    assert skyramp.get_response_value(orders_PUT_1_response, "Account__c") == "001g800000C3eLNAAZ"
    assert skyramp.get_response_value(orders_PUT_1_response, "LastModifiedDate") is not None

    # Step 6: Final verification of Approved status
    orders_GET_2_response = client.send_request(
        url=URL_playful_bear_m8hbtf_dev_ed,
        path="/services/apexrest/orders/{orders}",
        method="GET",
        headers=headers,
        path_params={"orders": orders}
    )
    assert orders_GET_2_response.status_code == 200
    assert skyramp.get_response_value(orders_GET_2_response, "Id") == skyramp.get_response_value(endpoint_1_POST_response, "Id")
    assert skyramp.get_response_value(orders_GET_2_response, "Status__c") == "Approved by Manufacturing"
    assert skyramp.get_response_value(orders_GET_2_response, "LastModifiedDate") is not None

    # # Step 7: Delete the order (cleanup)
    # orders_DELETE_response = client.send_request(
    #     url=URL_playful_bear_m8hbtf_dev_ed,
    #     path="/services/apexrest/orders/{orders}",
    #     method="DELETE",
    #     headers=headers,
    #     path_params={"orders": orders}
    # )
    # assert orders_DELETE_response.status_code == 204


if __name__ == "__main__":
    test_integration()
