# Generated by Skyramp v1.3.19 on 2026-04-23 19:40:58.816202 -0400 EDT m=+11982.495850751
# Command: skyramp generate integration rest \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--output order_with_line_items_integration_test.py \
# 		--output-dir /Users/koljaheck/Documents/Professional/Skyramp/ebikes-lwc/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /Users/koljaheck/Documents/Professional/Skyramp/ebikes-lwc/tests/scenario_order_with_line_items.json

# Import of required libraries
import skyramp
import json
import os
import time


# URL for test requests
URL_playful_bear_m8hbtf_dev_ed = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "https://playful-bear-m8hbtf-dev-ed.trailblaze.my.salesforce.com")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Step 1: Create parent order
    endpoint_2_POST_request_body = r'''{
        "Account__c": "001g800000C3eLNAAZ",
        "Status__c": "Draft"
    }'''

    endpoint_2_POST_response = client.send_request(
        url=URL_playful_bear_m8hbtf_dev_ed,
        path="/services/apexrest/orders/",
        method="POST",
        body=endpoint_2_POST_request_body,
        headers=headers
    )
    assert endpoint_2_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_2_POST_response, "Id") is not None
    assert skyramp.get_response_value(endpoint_2_POST_response, "Account__c") == "001g800000C3eLNAAZ"
    assert skyramp.get_response_value(endpoint_2_POST_response, "Status__c") == "Draft"
    assert skyramp.get_response_value(endpoint_2_POST_response, "LastModifiedDate") is not None

    order_id = skyramp.get_response_value(endpoint_2_POST_response, "Id")

    # Step 2: Create order item 1
    item1_request = json.dumps({
        "Order__c": order_id,
        "Product__c": "a03g800000ADlWkAAL",
        "Price__c": 2500,
        "Qty_S__c": 3,
        "Qty_M__c": 2,
        "Qty_L__c": 1
    })

    endpoint_1_POST_response = client.send_request(
        url=URL_playful_bear_m8hbtf_dev_ed,
        path="/services/apexrest/order-items/",
        method="POST",
        body=item1_request,
        headers=headers
    )
    assert endpoint_1_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_1_POST_response, "Id") is not None
    assert skyramp.get_response_value(endpoint_1_POST_response, "Order__c") == order_id
    assert skyramp.get_response_value(endpoint_1_POST_response, "Product__c") == "a03g800000ADlWkAAL"
    assert skyramp.get_response_value(endpoint_1_POST_response, "Price__c") == 2500
    assert skyramp.get_response_value(endpoint_1_POST_response, "Price__c") >= 0
    assert skyramp.get_response_value(endpoint_1_POST_response, "Qty_S__c") == 3
    assert skyramp.get_response_value(endpoint_1_POST_response, "Qty_M__c") == 2
    assert skyramp.get_response_value(endpoint_1_POST_response, "Qty_L__c") == 1

    item1_id = skyramp.get_response_value(endpoint_1_POST_response, "Id")

    # Step 3: Create order item 2
    item2_request = json.dumps({
        "Order__c": order_id,
        "Product__c": "a03g800000ADlWlAAL",
        "Price__c": 2600,
        "Qty_S__c": 5,
        "Qty_M__c": 4,
        "Qty_L__c": 3
    })

    endpoint_1_POST_1_response = client.send_request(
        url=URL_playful_bear_m8hbtf_dev_ed,
        path="/services/apexrest/order-items/",
        method="POST",
        body=item2_request,
        headers=headers
    )
    assert endpoint_1_POST_1_response.status_code == 201
    assert skyramp.get_response_value(endpoint_1_POST_1_response, "Id") is not None
    assert skyramp.get_response_value(endpoint_1_POST_1_response, "Order__c") == order_id
    assert skyramp.get_response_value(endpoint_1_POST_1_response, "Product__c") == "a03g800000ADlWlAAL"
    assert skyramp.get_response_value(endpoint_1_POST_1_response, "Price__c") == 2600
    assert skyramp.get_response_value(endpoint_1_POST_1_response, "Qty_S__c") == 5
    assert skyramp.get_response_value(endpoint_1_POST_1_response, "Qty_M__c") == 4
    assert skyramp.get_response_value(endpoint_1_POST_1_response, "Qty_L__c") == 3

    item2_id = skyramp.get_response_value(endpoint_1_POST_1_response, "Id")

    # Step 4: Get all order items filtered by orderId
    endpoint_1_GET_response = client.send_request(
        url=URL_playful_bear_m8hbtf_dev_ed,
        path=f"/services/apexrest/order-items/?orderId={order_id}",
        method="GET",
        headers=headers
    )
    assert endpoint_1_GET_response.status_code == 200

    # Step 5: Update item 1 quantities
    update_item1_body = r'''{
        "Qty_S__c": 10,
        "Qty_M__c": 8
    }'''

    order_items_PUT_response = client.send_request(
        url=URL_playful_bear_m8hbtf_dev_ed,
        path=f"/services/apexrest/order-items/{item1_id}",
        method="PUT",
        body=update_item1_body,
        headers=headers
    )
    assert order_items_PUT_response.status_code == 200
    assert skyramp.get_response_value(order_items_PUT_response, "Id") == item1_id
    assert skyramp.get_response_value(order_items_PUT_response, "Qty_S__c") == 10
    assert skyramp.get_response_value(order_items_PUT_response, "Qty_M__c") == 8

    # Step 6: Delete item 2
    order_items_DELETE_response = client.send_request(
        url=URL_playful_bear_m8hbtf_dev_ed,
        path=f"/services/apexrest/order-items/{item2_id}",
        method="DELETE",
        headers=headers
    )
    assert order_items_DELETE_response.status_code == 204

    # Step 7: Get order items again - verify only item 1 remains
    endpoint_1_GET_1_response = client.send_request(
        url=URL_playful_bear_m8hbtf_dev_ed,
        path=f"/services/apexrest/order-items/?orderId={order_id}",
        method="GET",
        headers=headers
    )
    assert endpoint_1_GET_1_response.status_code == 200

    # Step 8: Cleanup - delete item 1
    order_items_DELETE_1_response = client.send_request(
        url=URL_playful_bear_m8hbtf_dev_ed,
        path=f"/services/apexrest/order-items/{item1_id}",
        method="DELETE",
        headers=headers
    )
    assert order_items_DELETE_1_response.status_code == 204

    # Step 9: Cleanup - delete parent order
    orders_DELETE_response = client.send_request(
        url=URL_playful_bear_m8hbtf_dev_ed,
        path=f"/services/apexrest/orders/{order_id}",
        method="DELETE",
        headers=headers
    )
    assert orders_DELETE_response.status_code == 204


if __name__ == "__main__":
    test_integration()
