# Generated by Skyramp v1.3.18 on 2026-04-24 20:58:29.262704655 +0000 UTC m=+15.416944555
# Command: skyramp generate integration rest \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--output order_items_lifecycle_integration_test.py \
# 		--output-dir /home/runner/work/ebikes-lwc/ebikes-lwc/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/ebikes-lwc/ebikes-lwc/tests/scenario_order-items-lifecycle.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_playful_bear_m8hbtf_dev_ed = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "https://playful-bear-m8hbtf-dev-ed.trailblaze.my.salesforce.com")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    endpoint_2_POST_request_body = r'''{
        "Account__c": "001g800000C3eLNAAZ",
        "Status__c": "Draft"
    }'''

    # Execute Request
    endpoint_2_POST_response = client.send_request(
        url=URL_playful_bear_m8hbtf_dev_ed,
        path="/services/apexrest/orders/",
        method="POST",
        body=endpoint_2_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_2_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_2_POST_response, "Id") is not None

    parent_order_id = skyramp.get_response_value(endpoint_2_POST_response, "Id")

    # Request Body
    import json
    endpoint_1_POST_request_body = json.dumps({
        "Order__c": parent_order_id,
        "Product__c": "a03g800000ADlWkAAL",
        "Price__c": 2999,
        "Qty_S__c": 5,
        "Qty_M__c": 3,
        "Qty_L__c": 2
    })

    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_playful_bear_m8hbtf_dev_ed,
        path="/services/apexrest/order-items/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_1_POST_response, "Id") is not None
    assert skyramp.get_response_value(endpoint_1_POST_response, "Name") is not None
    assert skyramp.get_response_value(endpoint_1_POST_response, "Order__c") == parent_order_id
    assert skyramp.get_response_value(endpoint_1_POST_response, "Product__c") == "a03g800000ADlWkAAL"
    assert skyramp.get_response_value(endpoint_1_POST_response, "Price__c") == 2999
    assert skyramp.get_response_value(endpoint_1_POST_response, "Price__c") >= 0
    assert skyramp.get_response_value(endpoint_1_POST_response, "Qty_S__c") == 5
    assert skyramp.get_response_value(endpoint_1_POST_response, "Qty_M__c") == 3
    assert skyramp.get_response_value(endpoint_1_POST_response, "Qty_L__c") == 2


if __name__ == "__main__":
    test_integration()
