# Generated by Skyramp v1.3.18 on 2026-04-24 18:58:15.442816632 +0000 UTC m=+77.497085393
# Command: skyramp generate integration rest \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--output order_invalid_transition_integration_test.py \
# 		--output-dir /home/runner/work/ebikes-lwc/ebikes-lwc/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/ebikes-lwc/ebikes-lwc/tests/scenario_order-invalid-transition.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_playful_bear_m8hbtf_dev_ed = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "https://playful-bear-m8hbtf-dev-ed.trailblaze.my.salesforce.com")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    endpoint_1_POST_request_body = r'''{
        "Account__c": "001g800000C3eLNAAZ",
        "Status__c": "Draft"
    }'''

    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_playful_bear_m8hbtf_dev_ed,
        path="/services/apexrest/orders/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_1_POST_response, "Id") is not None
    assert skyramp.get_response_value(endpoint_1_POST_response, "Status__c") == "Draft"
    assert skyramp.get_response_value(endpoint_1_POST_response, "Account__c") == "001g800000C3eLNAAZ"

    orders = skyramp.get_response_value(endpoint_1_POST_response, "Id")

    # Request Body
    orders_PUT_request_body = r'''{
        "Status__c": "Approved by Manufacturing"
    }'''

    # Execute Request
    orders_PUT_response = client.send_request(
        url=URL_playful_bear_m8hbtf_dev_ed,
        path="/services/apexrest/orders/{orders}",
        method="PUT",
        body=orders_PUT_request_body,
        headers=headers,
        path_params={"orders": orders}
    )
    # Generated Assertions
    assert orders_PUT_response.status_code == 400


if __name__ == "__main__":
    test_integration()
