# Generated by Skyramp v1.3.18 on 2026-04-24 19:01:16.538593575 +0000 UTC m=+29.520108295
# Command: skyramp generate integration rest \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--output order_multi_item_totals_integration_test.py \
# 		--output-dir /home/runner/work/ebikes-lwc/ebikes-lwc/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/ebikes-lwc/ebikes-lwc/tests/scenario_order-multi-item-totals.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_playful_bear_m8hbtf_dev_ed = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "https://playful-bear-m8hbtf-dev-ed.trailblaze.my.salesforce.com")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    endpoint_2_POST_request_body = r'''{
        "Account__c": "001g800000C3eLNAAZ",
        "Status__c": "Draft"
    }'''

    # Execute Request
    endpoint_2_POST_response = client.send_request(
        url=URL_playful_bear_m8hbtf_dev_ed,
        path="/services/apexrest/orders/",
        method="POST",
        body=endpoint_2_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_2_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_2_POST_response, "Id") is not None
    assert skyramp.get_response_value(endpoint_2_POST_response, "Status__c") == "Draft"
    assert skyramp.get_response_value(endpoint_2_POST_response, "Account__c") == "001g800000C3eLNAAZ"

    # Chain order ID for subsequent requests
    orders = skyramp.get_response_value(endpoint_2_POST_response, "Id")

    # Request Body
    endpoint_1_POST_request_body = r'''{
        "Order__c": "a01FAKE000002",
        "Price__c": 1999,
        "Product__c": "a03g800000ADlWkAAL",
        "Qty_L__c": 0,
        "Qty_M__c": 0,
        "Qty_S__c": 1
    }'''

    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_playful_bear_m8hbtf_dev_ed,
        path="/services/apexrest/order-items/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers=headers,
        data_override={"Order__c": orders}
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_1_POST_response, "Id") is not None
    assert skyramp.get_response_value(endpoint_1_POST_response, "Order__c") == orders
    assert skyramp.get_response_value(endpoint_1_POST_response, "Price__c") == 1999
    assert skyramp.get_response_value(endpoint_1_POST_response, "Qty_S__c") == 1

    # Request Body
    endpoint_1_POST_1_request_body = r'''{
        "Order__c": "a01FAKE000002",
        "Price__c": 2999,
        "Product__c": "a03g800000ADlWkAAL",
        "Qty_L__c": 0,
        "Qty_M__c": 0,
        "Qty_S__c": 2
    }'''

    # Execute Request
    endpoint_1_POST_1_response = client.send_request(
        url=URL_playful_bear_m8hbtf_dev_ed,
        path="/services/apexrest/order-items/",
        method="POST",
        body=endpoint_1_POST_1_request_body,
        headers=headers,
        data_override={"Order__c": orders}
    )
    # Generated Assertions
    assert endpoint_1_POST_1_response.status_code == 201
    assert skyramp.get_response_value(endpoint_1_POST_1_response, "Id") is not None
    assert skyramp.get_response_value(endpoint_1_POST_1_response, "Order__c") == orders
    assert skyramp.get_response_value(endpoint_1_POST_1_response, "Price__c") == 2999
    assert skyramp.get_response_value(endpoint_1_POST_1_response, "Qty_S__c") == 2

    # Execute Request
    orders_GET_response = client.send_request(
        url=URL_playful_bear_m8hbtf_dev_ed,
        path="/services/apexrest/orders/{orders}",
        method="GET",
        headers=headers,
        path_params={"orders": orders}
    )
    # Generated Assertions
    assert orders_GET_response.status_code == 200
    assert skyramp.get_response_value(orders_GET_response, "Id") == orders
    assert skyramp.get_response_value(orders_GET_response, "Status__c") == "Draft"
    assert skyramp.get_response_value(orders_GET_response, "Account__c") == "001g800000C3eLNAAZ"
    assert skyramp.get_response_value(orders_GET_response, "Order_Total") is not None
    assert skyramp.get_response_value(orders_GET_response, "Order_Total") == (skyramp.get_response_value(endpoint_1_POST_response, "Price__c") * skyramp.get_response_value(endpoint_1_POST_response, "Qty_S__c")) + (skyramp.get_response_value(endpoint_1_POST_1_response, "Price__c") * skyramp.get_response_value(endpoint_1_POST_1_response, "Qty_S__c"))
    assert skyramp.get_response_value(orders_GET_response, "Item_Count") is not None
    assert skyramp.get_response_value(orders_GET_response, "Item_Count") == 2


if __name__ == "__main__":
    test_integration()
