# Generated by Skyramp v1.3.19 on 2026-04-23 19:40:59.614375 -0400 EDT m=+11983.294029668
# Command: skyramp generate integration rest \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--output product_crud_integration_test.py \
# 		--output-dir /Users/koljaheck/Documents/Professional/Skyramp/ebikes-lwc/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /Users/koljaheck/Documents/Professional/Skyramp/ebikes-lwc/tests/scenario_product_crud.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_playful_bear_m8hbtf_dev_ed = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "https://playful-bear-m8hbtf-dev-ed.trailblaze.my.salesforce.com")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Step 1: Create product
    endpoint_1_POST_request_body = r'''{
        "Category__c": "Mountain",
        "Description__c": "High-performance test bike",
        "Level__c": "Racer",
        "MSRP__c": 3499,
        "Material__c": "Carbon",
        "Name": "Integration Test Bike Z1",
        "Picture_URL__c": "https://example.com/z1.png"
    }'''

    endpoint_1_POST_response = client.send_request(
        url=URL_playful_bear_m8hbtf_dev_ed,
        path="/services/apexrest/products/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers=headers
    )
    assert endpoint_1_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_1_POST_response, "Id") is not None
    assert skyramp.get_response_value(endpoint_1_POST_response, "Name") == "Integration Test Bike Z1"
    assert skyramp.get_response_value(endpoint_1_POST_response, "Category__c") == "Mountain"
    assert skyramp.get_response_value(endpoint_1_POST_response, "Level__c") == "Racer"
    assert skyramp.get_response_value(endpoint_1_POST_response, "MSRP__c") == 3499
    assert skyramp.get_response_value(endpoint_1_POST_response, "Material__c") == "Carbon"

    # Dynamic ID from POST response
    product_id = skyramp.get_response_value(endpoint_1_POST_response, "Id")

    # Step 2: Get product by ID
    products_GET_response = client.send_request(
        url=URL_playful_bear_m8hbtf_dev_ed,
        path=f"/services/apexrest/products/{product_id}",
        method="GET",
        headers=headers
    )
    assert products_GET_response.status_code == 200
    assert skyramp.get_response_value(products_GET_response, "Id") == product_id
    assert skyramp.get_response_value(products_GET_response, "Name") == "Integration Test Bike Z1"
    assert skyramp.get_response_value(products_GET_response, "Category__c") == "Mountain"
    assert skyramp.get_response_value(products_GET_response, "Level__c") == "Racer"
    assert skyramp.get_response_value(products_GET_response, "MSRP__c") == 3499
    assert skyramp.get_response_value(products_GET_response, "Material__c") == "Carbon"

    # Step 3: Update product (change MSRP and Category)
    products_PUT_request_body = r'''{
        "Category__c": "Commuter",
        "MSRP__c": 2999
    }'''

    products_PUT_response = client.send_request(
        url=URL_playful_bear_m8hbtf_dev_ed,
        path=f"/services/apexrest/products/{product_id}",
        method="PUT",
        body=products_PUT_request_body,
        headers=headers
    )
    assert products_PUT_response.status_code == 200
    assert skyramp.get_response_value(products_PUT_response, "Id") == product_id
    assert skyramp.get_response_value(products_PUT_response, "Category__c") == "Commuter"
    assert skyramp.get_response_value(products_PUT_response, "MSRP__c") == 2999
    assert skyramp.get_response_value(products_PUT_response, "Name") == "Integration Test Bike Z1"

    # Step 4: Get product again to verify updates persisted
    products_GET_1_response = client.send_request(
        url=URL_playful_bear_m8hbtf_dev_ed,
        path=f"/services/apexrest/products/{product_id}",
        method="GET",
        headers=headers
    )
    assert products_GET_1_response.status_code == 200
    assert skyramp.get_response_value(products_GET_1_response, "Id") == product_id
    assert skyramp.get_response_value(products_GET_1_response, "Category__c") == "Commuter"
    assert skyramp.get_response_value(products_GET_1_response, "MSRP__c") == 2999
    assert skyramp.get_response_value(products_GET_1_response, "Name") == "Integration Test Bike Z1"
    assert skyramp.get_response_value(products_GET_1_response, "Level__c") == "Racer"
    assert skyramp.get_response_value(products_GET_1_response, "Material__c") == "Carbon"

    # Step 5: Delete product
    products_DELETE_response = client.send_request(
        url=URL_playful_bear_m8hbtf_dev_ed,
        path=f"/services/apexrest/products/{product_id}",
        method="DELETE",
        headers=headers
    )
    assert products_DELETE_response.status_code == 204

    # Step 6: Verify product is gone (404)
    products_GET_2_response = client.send_request(
        url=URL_playful_bear_m8hbtf_dev_ed,
        path=f"/services/apexrest/products/{product_id}",
        method="GET",
        headers=headers
    )
    assert products_GET_2_response.status_code == 404


if __name__ == "__main__":
    test_integration()
