// Generated by Skyramp v1.3.18 on 2026-04-24 19:00:59.292393987 +0000 UTC m=+377.891923359
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output product_explorer_star_display.spec.ts \
// 		--output-dir /home/runner/work/ebikes-lwc/ebikes-lwc/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/ebikes-lwc/ebikes-lwc/.skyramp/product_explorer_star_display_trace.zip

// Import of required libraries
import { test, expect } from '@playwright/test';
import { newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(60000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const errors: string[] = [];
    page.on('pageerror', (err) => errors.push(err.message));

    await page.goto("https://playful-bear-m8hbtf-dev-ed.trailblaze.my.site.com/ebikes/s/");
    await page.waitForLoadState('networkidle');

    await page.goto("https://playful-bear-m8hbtf-dev-ed.trailblaze.my.site.com/ebikes/s/product-explorer");
    await page.waitForLoadState('networkidle');

    await expect(page.getByRole('link', { name: 'Product Explorer' })).toBeVisible();
    await expect(page.getByRole('heading', { name: 'Error retrieving data' })).not.toBeVisible();

    expect(errors).toHaveLength(0);
});
