// Generated by Skyramp v1.3.18 on 2026-04-24 19:02:48.924290663 +0000 UTC m=+121.905805393
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output product_tile_description_ui_test.spec.ts \
// 		--output-dir /home/runner/work/ebikes-lwc/ebikes-lwc/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/ebikes-lwc/ebikes-lwc/.skyramp/product_tile_description_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(213000);

    const errors: string[] = [];
    page.on('pageerror', (err) => errors.push(err.message));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("https://playful-bear-m8hbtf-dev-ed.trailblaze.my.site.com/ebikes/s/product-explorer");
    await page.waitForLoadState('networkidle');
    await page.getByText("items • page 1 of 2").waitFor({ state: 'visible', timeout: 15000 });

    await expect(page.getByText("items • page 1 of 2")).toContainText("17 items");

    // Assert that product tiles display description text below the product name
    // This assertion validates the productTile UI change that adds Description field display
    await expect(page.locator('c-product-tile').first()).toBeVisible();
    const firstTile = page.locator('c-product-tile').first();
    await expect(firstTile.locator('.description, [class*="description"], p + p:not(:last-child)')).toBeVisible();

    expect(errors).toHaveLength(0);
});
