// Generated by Skyramp v1.3.18 on 2026-04-24 18:39:15.522796185 +0000 UTC m=+154.080569280
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output product_level_badge_ui_test.spec.ts \
// 		--output-dir /home/runner/work/ebikes-lwc/ebikes-lwc/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/ebikes-lwc/ebikes-lwc/.skyramp/product_level_badge_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(135000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const errors: string[] = [];
    page.on('pageerror', (err) => errors.push(err.message));

    await page.goto("https://playful-bear-m8hbtf-dev-ed.trailblaze.my.salesforce.com/ebikes/s/");
    await page.goto("https://playful-bear-m8hbtf-dev-ed.trailblaze.my.salesforce.com/ebikes/");
    await page.goto("https://playful-bear-m8hbtf-dev-ed.trailblaze.my.salesforce.com/EBikesStore/");
    await page.goto("https://playful-bear-m8hbtf-dev-ed.trailblaze.my.site.com/ebikes/s/");
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.goto("https://playful-bear-m8hbtf-dev-ed.trailblaze.my.site.com/ebikes/s/product-explorer");
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await expect(page.getByText("items • page 1 of 2")).toContainText("17 items");
    await expect(page.getByText("Racer").first()).toBeVisible();
    await expect(page.getByText("Beginner").first()).toBeVisible();
    await expect(page.getByText("Enthusiast").first()).toBeVisible();
    expect(errors).toHaveLength(0);
});
