# Generated by Skyramp v1.3.18 on 2026-04-24 18:57:54.06366192 +0000 UTC m=+192.663191282
# Command: skyramp generate integration rest \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--output products_rating_lifecycle_integration_test.py \
# 		--output-dir /home/runner/work/ebikes-lwc/ebikes-lwc/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/ebikes-lwc/ebikes-lwc/tests/scenario_products-rating-lifecycle.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_playful_bear_m8hbtf_dev_ed = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "https://playful-bear-m8hbtf-dev-ed.trailblaze.my.salesforce.com")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    endpoint_1_POST_request_body = r'''{
        "Category__c": "Mountain",
        "Level__c": "Beginner",
        "MSRP__c": 1299.99,
        "Name": "Test E-Bike Rating-1714000000",
        "Rating__c": 3.7
    }'''
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_playful_bear_m8hbtf_dev_ed,
        path="/services/apexrest/products/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_1_POST_response, "Id") is not None
    assert skyramp.get_response_value(endpoint_1_POST_response, "Name") == "Test E-Bike Rating-1714000000"
    assert skyramp.get_response_value(endpoint_1_POST_response, "Rating__c") == 3.7
    assert skyramp.get_response_value(endpoint_1_POST_response, "MSRP__c") >= 0
    assert skyramp.get_response_value(endpoint_1_POST_response, "Category__c") == "Mountain"

    # Execute Request
    products_GET_response = client.send_request(
        url=URL_playful_bear_m8hbtf_dev_ed,
        path="/services/apexrest/products/{products}",
        method="GET",
        headers=headers,
        path_params={"products": skyramp.get_response_value(endpoint_1_POST_response, "Id")}
    )
    # Generated Assertions
    assert products_GET_response.status_code == 200
    assert skyramp.get_response_value(products_GET_response, "Id") == skyramp.get_response_value(endpoint_1_POST_response, "Id")
    assert skyramp.get_response_value(products_GET_response, "Rating__c") == skyramp.get_response_value(endpoint_1_POST_response, "Rating__c")
    assert skyramp.get_response_value(products_GET_response, "Name") == skyramp.get_response_value(endpoint_1_POST_response, "Name")

    # Execute Request
    products_DELETE_response = client.send_request(
        url=URL_playful_bear_m8hbtf_dev_ed,
        path="/services/apexrest/products/{products}",
        method="DELETE",
        headers=headers,
        path_params={"products": skyramp.get_response_value(endpoint_1_POST_response, "Id")}
    )
    # Generated Assertions
    assert products_DELETE_response.status_code == 204


if __name__ == "__main__":
    test_integration()
